[book]
title = "Rouge's Notes"
author = "Rouge Lin"
language = "zh-CN"
multilingual = false
src = "src"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
site-url = "/notes/"
git-repository-url = "https://github.com/rouge3877/notes"
git-repository-icon = "fa-github"

[output.html.mathjax-support]
enable = true
